const ingredient = (name, amount, unit, category, basePrice) => ({
  name,
  amount,
  unit,
  category,
  basePrice,
});

const dish = (id, name, emoji, time, effort, tags, trendNote, sources, ingredients) => ({
  id,
  name,
  emoji,
  time,
  effort,
  tags,
  trendNote,
  sources,
  ingredients,
});

export const DISH_POOL = [
  dish("spicy-vodka-gemelli", "Spicy Vodka Gemelli", "🍝", 30, "easy", ["quick", "cozy", "spicy"], "Creamy, spicy pasta still wins the internet every single week.", ["Recipe sites", "Pinterest", "Reels"], [
    ingredient("gemelli pasta", 1, "box", "pantry", 3.25),
    ingredient("vodka sauce", 1, "jar", "pantry", 4.9),
    ingredient("calabrian chili paste", 1, "jar", "specialty", 6.5),
    ingredient("shallots", 2, "piece", "produce", 1.1),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("crispy-rice-salmon-bowls", "Crispy Rice Salmon Bowls", "🍣", 35, "medium", ["spicy", "dinner-party"], "Crunchy rice, glossy salmon, and spicy mayo keep trending for good reason.", ["Food blogs", "Pinterest", "Short-form video"], [
    ingredient("salmon fillets", 2, "lb", "seafood", 11.5),
    ingredient("jasmine rice", 1, "bag", "pantry", 4.5),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("avocados", 2, "piece", "produce", 1.7),
    ingredient("spicy mayo", 1, "bottle", "specialty", 5.9),
  ]),
  dish("chili-crisp-gnocchi", "Chili Crisp Gnocchi", "🥔", 25, "easy", ["quick", "cozy", "spicy", "veg"], "Pan-fried gnocchi and chili crisp are the kind of lazy luxury people replay.", ["Recipe sites", "TikTok-style video", "Pinterest"], [
    ingredient("shelf-stable gnocchi", 2, "pack", "pantry", 3.5),
    ingredient("chili crisp", 1, "jar", "specialty", 6.4),
    ingredient("spinach", 1, "bag", "produce", 2.9),
    ingredient("garlic", 1, "bulb", "produce", 0.8),
    ingredient("pecorino", 1, "tub", "dairy", 6.2),
  ]),
  dish("sheet-pan-shawarma-chicken", "Sheet-Pan Shawarma Chicken", "🍗", 40, "easy", ["dinner-party", "protein"], "Sheet-pan dinner plus big sauces equals weeknight content gold.", ["Recipe sites", "Pinterest", "Instagram creators"], [
    ingredient("chicken thighs", 2, "lb", "protein", 6.8),
    ingredient("naan", 1, "pack", "bakery", 4.2),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("shawarma seasoning", 1, "jar", "specialty", 5.6),
  ]),
  dish("green-goddess-wraps", "Green Goddess Chopped Wraps", "🥬", 20, "easy", ["quick", "veg"], "Chopped crunchy lunches keep popping because they look fresh and expensive.", ["Pinterest", "Lunch blogs", "Reels"], [
    ingredient("large tortillas", 1, "pack", "bakery", 3.8),
    ingredient("romaine hearts", 1, "bag", "produce", 3.2),
    ingredient("avocados", 2, "piece", "produce", 1.7),
    ingredient("green goddess dressing", 1, "bottle", "specialty", 4.9),
    ingredient("white beans", 2, "can", "pantry", 1.3),
  ]),
  dish("hot-honey-halloumi-tacos", "Hot Honey Halloumi Tacos", "🌮", 25, "easy", ["quick", "veg", "spicy"], "Sweet heat plus squeaky cheese keeps landing in recipe roundups.", ["Recipe sites", "Pinterest", "Instagram"], [
    ingredient("halloumi", 2, "block", "dairy", 5.8),
    ingredient("small tortillas", 1, "pack", "bakery", 3.6),
    ingredient("hot honey", 1, "bottle", "specialty", 5.5),
    ingredient("red cabbage", 1, "head", "produce", 2.8),
    ingredient("limes", 3, "piece", "produce", 0.7),
  ]),
  dish("miso-butter-mushroom-udon", "Miso Butter Mushroom Udon", "🍜", 25, "easy", ["quick", "cozy", "veg"], "Savory butter noodles with mushrooms are everywhere because they feel restaurant-y.", ["Recipe sites", "Pinterest", "Video"], [
    ingredient("frozen udon", 2, "pack", "frozen", 4.4),
    ingredient("mushrooms", 2, "box", "produce", 2.9),
    ingredient("white miso", 1, "tub", "specialty", 5.7),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
    ingredient("butter", 1, "box", "dairy", 4.4),
  ]),
  dish("smash-burger-salad", "Smash Burger Salad", "🥗", 25, "easy", ["quick", "protein"], "Burger flavors in a salad bowl still hit when everyone wants lighter comfort food.", ["Blogs", "Instagram", "Pinterest"], [
    ingredient("ground beef", 2, "lb", "protein", 6.4),
    ingredient("romaine hearts", 1, "bag", "produce", 3.2),
    ingredient("cheddar", 1, "bag", "dairy", 4.6),
    ingredient("pickles", 1, "jar", "pantry", 3.8),
    ingredient("burger sauce", 1, "bottle", "specialty", 4.9),
  ]),
  dish("lemony-orzo-chicken", "Lemony Orzo Chicken Skillet", "🍋", 30, "easy", ["quick", "cozy", "protein"], "One-pan lemony pastas always trend because they promise low cleanup.", ["Recipe sites", "Pinterest", "Reels"], [
    ingredient("orzo", 1, "box", "pantry", 2.9),
    ingredient("chicken breast", 2, "lb", "protein", 7.2),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("lemons", 2, "piece", "produce", 0.8),
    ingredient("feta", 1, "tub", "dairy", 4.9),
  ]),
  dish("birria-grilled-cheese", "Birria Grilled Cheese Melts", "🧀", 35, "medium", ["cozy", "spicy"], "Messy, dunkable sandwiches are still pure clickbait in the best way.", ["Pinterest", "Short-form video", "Recipe sites"], [
    ingredient("sourdough loaf", 1, "loaf", "bakery", 5.6),
    ingredient("shredded chuck roast", 2, "lb", "protein", 8.8),
    ingredient("oaxaca cheese", 1, "pack", "dairy", 5.9),
    ingredient("birria simmer sauce", 1, "jar", "specialty", 6.5),
    ingredient("yellow onions", 2, "piece", "produce", 1.0),
  ]),
  dish("pesto-white-bean-toast", "Pesto White Bean Toast Board", "🥖", 15, "easy", ["quick", "veg"], "Snacky dinner boards keep doing numbers because they are low effort but photogenic.", ["Instagram", "Pinterest", "Lunch blogs"], [
    ingredient("ciabatta", 1, "loaf", "bakery", 4.8),
    ingredient("white beans", 2, "can", "pantry", 1.3),
    ingredient("basil pesto", 1, "jar", "specialty", 5.5),
    ingredient("cherry tomatoes", 1, "box", "produce", 3.2),
    ingredient("burrata", 1, "tub", "dairy", 6.7),
  ]),
  dish("korean-corn-cheese-bowls", "Korean Corn Cheese Rice Bowls", "🌽", 20, "easy", ["quick", "cozy", "spicy", "veg"], "Sweet corn, cheese pulls, and spicy sauce is internet comfort food math.", ["Video", "Pinterest", "Recipe sites"], [
    ingredient("short grain rice", 1, "bag", "pantry", 4.8),
    ingredient("frozen corn", 1, "bag", "frozen", 3.1),
    ingredient("mozzarella", 1, "bag", "dairy", 4.5),
    ingredient("gochujang", 1, "tub", "specialty", 5.9),
    ingredient("kimchi", 1, "jar", "specialty", 6.1),
  ]),
  dish("coconut-curry-dumpling-soup", "Coconut Curry Dumpling Soup", "🥟", 25, "easy", ["quick", "cozy", "veg"], "Brothy dumpling bowls feel special while still being freezer-friendly.", ["Recipe sites", "Pinterest", "Video"], [
    ingredient("frozen dumplings", 2, "bag", "frozen", 6.4),
    ingredient("coconut milk", 2, "can", "pantry", 2.8),
    ingredient("red curry paste", 1, "jar", "specialty", 5.2),
    ingredient("baby bok choy", 2, "head", "produce", 2.2),
    ingredient("lime", 2, "piece", "produce", 0.7),
  ]),
  dish("crispy-feta-farro", "Crispy Feta Carrot Farro", "🥕", 35, "easy", ["veg", "dinner-party"], "Roasted veg plus salty cheese keeps showing up in glossy save-worthy posts.", ["Pinterest", "Recipe sites", "Instagram"], [
    ingredient("farro", 1, "bag", "pantry", 4.8),
    ingredient("rainbow carrots", 1, "bag", "produce", 3.6),
    ingredient("feta block", 1, "block", "dairy", 5.1),
    ingredient("mint", 1, "bunch", "produce", 1.9),
    ingredient("pistachios", 1, "bag", "pantry", 6.7),
  ]),
  dish("shrimp-taco-bowls", "Shrimp Taco Bowls with Mango Slaw", "🍤", 25, "easy", ["quick", "spicy", "seafood"], "Shrimp bowls stay popular because they feel fresh and fast.", ["Recipe sites", "Pinterest", "Reels"], [
    ingredient("shrimp", 2, "lb", "seafood", 10.2),
    ingredient("cilantro lime rice", 1, "bag", "pantry", 4.9),
    ingredient("mango", 2, "piece", "produce", 1.8),
    ingredient("coleslaw mix", 1, "bag", "produce", 2.9),
    ingredient("chipotle crema", 1, "bottle", "specialty", 4.9),
  ]),
  dish("onion-miso-pasta", "Caramelized Onion Miso Pasta", "🧅", 35, "easy", ["cozy", "veg"], "Sweet onions and savory miso hit that restaurant pasta mood people save.", ["Blogs", "Pinterest", "Instagram"], [
    ingredient("spaghetti", 1, "box", "pantry", 2.4),
    ingredient("yellow onions", 3, "piece", "produce", 1.0),
    ingredient("white miso", 1, "tub", "specialty", 5.7),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
    ingredient("thyme", 1, "bunch", "produce", 1.8),
  ]),
  dish("sesame-ginger-meatballs", "Sesame Ginger Chicken Meatballs", "🍘", 30, "easy", ["quick", "protein"], "Sticky meatball bowls have become permanent meal-prep content.", ["Pinterest", "Meal-prep blogs", "Video"], [
    ingredient("ground chicken", 2, "lb", "protein", 6.1),
    ingredient("jasmine rice", 1, "bag", "pantry", 4.5),
    ingredient("broccoli florets", 2, "bag", "produce", 3.3),
    ingredient("sesame ginger sauce", 1, "bottle", "specialty", 5.3),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
  ]),
  dish("elote-pasta-salad", "Elote Pasta Salad", "🌽", 25, "easy", ["veg", "dinner-party"], "Street-corn flavors in pasta salad are summer-share magnets.", ["Recipe sites", "Pinterest", "Instagram"], [
    ingredient("fusilli", 1, "box", "pantry", 2.9),
    ingredient("corn", 4, "piece", "produce", 0.8),
    ingredient("cotija", 1, "pack", "dairy", 4.8),
    ingredient("lime", 3, "piece", "produce", 0.7),
    ingredient("tajin", 1, "jar", "specialty", 3.9),
  ]),
  dish("tofu-banh-mi-bowls", "Crispy Tofu Banh Mi Bowls", "🥢", 30, "medium", ["veg", "spicy"], "Pickly, crunchy, spicy bowls get saved fast because the contrast is so photogenic.", ["Recipe sites", "Pinterest", "Creator posts"], [
    ingredient("extra firm tofu", 2, "block", "protein", 2.9),
    ingredient("jasmine rice", 1, "bag", "pantry", 4.5),
    ingredient("pickled carrots", 1, "jar", "specialty", 4.6),
    ingredient("cucumber", 2, "piece", "produce", 1.2),
    ingredient("sriracha mayo", 1, "bottle", "specialty", 4.9),
  ]),
  dish("vodka-meatball-subs", "Vodka Meatball Subs", "🥖", 35, "easy", ["cozy", "protein"], "Big saucy sandwiches are still a foolproof viral dinner format.", ["Recipe sites", "Pinterest", "Video"], [
    ingredient("sub rolls", 1, "pack", "bakery", 4.7),
    ingredient("turkey meatballs", 2, "bag", "frozen", 6.2),
    ingredient("vodka sauce", 1, "jar", "pantry", 4.9),
    ingredient("mozzarella", 1, "bag", "dairy", 4.5),
    ingredient("basil", 1, "bunch", "produce", 2.1),
  ]),
  dish("buffalo-chickpea-flatbreads", "Buffalo Chickpea Flatbreads", "🌶️", 20, "easy", ["quick", "veg", "spicy"], "Buffalo everything still wins when people want playful weeknight food.", ["Pinterest", "Lunch blogs", "Instagram"], [
    ingredient("flatbreads", 1, "pack", "bakery", 4.8),
    ingredient("chickpeas", 2, "can", "pantry", 1.2),
    ingredient("buffalo sauce", 1, "bottle", "specialty", 4.2),
    ingredient("ranch dressing", 1, "bottle", "specialty", 4.3),
    ingredient("celery", 1, "bunch", "produce", 2.0),
  ]),
  dish("pesto-burrata-pizza", "Pesto Burrata Pizza", "🍕", 25, "easy", ["veg", "dinner-party"], "Cheese-pull pizza nights are built for sharing and saving.", ["Recipe sites", "Pinterest", "Instagram"], [
    ingredient("pizza dough", 2, "ball", "bakery", 3.9),
    ingredient("basil pesto", 1, "jar", "specialty", 5.5),
    ingredient("burrata", 2, "tub", "dairy", 6.7),
    ingredient("cherry tomatoes", 1, "box", "produce", 3.2),
    ingredient("arugula", 1, "bag", "produce", 3.4),
  ]),
  dish("kimchi-grilled-cheese-soup", "Kimchi Grilled Cheese & Tomato Soup", "🥣", 25, "easy", ["cozy", "spicy", "veg"], "Fermented crunch in grilled cheese keeps getting rediscovered online.", ["Blogs", "Pinterest", "Video"], [
    ingredient("sourdough loaf", 1, "loaf", "bakery", 5.6),
    ingredient("kimchi", 1, "jar", "specialty", 6.1),
    ingredient("cheddar", 1, "bag", "dairy", 4.6),
    ingredient("tomato soup", 2, "carton", "pantry", 3.6),
    ingredient("butter", 1, "box", "dairy", 4.4),
  ]),
  dish("harissa-salmon-couscous", "Harissa Salmon Couscous", "🐟", 30, "easy", ["dinner-party", "spicy", "seafood"], "Bright spicy salmon with fluffy grains reads fancy without much work.", ["Recipe sites", "Pinterest", "Instagram"], [
    ingredient("salmon fillets", 2, "lb", "seafood", 11.5),
    ingredient("couscous", 1, "box", "pantry", 3.2),
    ingredient("harissa", 1, "jar", "specialty", 5.9),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("street-corn-gnocchi-skillet", "Street Corn Gnocchi Skillet", "🧈", 25, "easy", ["cozy", "veg"], "Corn plus creamy gnocchi is exactly the sort of hybrid comfort food that spreads.", ["Pinterest", "Recipe sites", "Video"], [
    ingredient("shelf-stable gnocchi", 2, "pack", "pantry", 3.5),
    ingredient("corn", 4, "piece", "produce", 0.8),
    ingredient("cotija", 1, "pack", "dairy", 4.8),
    ingredient("jalapenos", 2, "piece", "produce", 0.7),
    ingredient("lime", 2, "piece", "produce", 0.7),
  ]),
  dish("tandoori-chicken-naan", "Tandoori Chicken Naan Wraps", "🌯", 30, "easy", ["spicy", "protein", "dinner-party"], "Colorful wraps and creamy sauces are still made for social feeds.", ["Recipe sites", "Pinterest", "Creator posts"], [
    ingredient("chicken breast", 2, "lb", "protein", 7.2),
    ingredient("naan", 1, "pack", "bakery", 4.2),
    ingredient("tandoori simmer sauce", 1, "jar", "specialty", 6.3),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("turkey-taco-soup", "Green Chile Turkey Taco Soup", "🍲", 30, "easy", ["cozy", "protein"], "Soup with taco toppings keeps getting saved because it feels flexible and easy.", ["Recipe sites", "Pinterest", "Meal-prep"], [
    ingredient("ground turkey", 2, "lb", "protein", 5.9),
    ingredient("green chiles", 2, "can", "pantry", 1.8),
    ingredient("black beans", 2, "can", "pantry", 1.3),
    ingredient("chicken broth", 2, "carton", "pantry", 2.9),
    ingredient("avocados", 2, "piece", "produce", 1.7),
  ]),
  dish("crispy-potato-caesar", "Crispy Potato Caesar Bowls", "🥔", 30, "easy", ["quick", "veg"], "Warm roasted potatoes in a caesar bowl has been everywhere lately.", ["Pinterest", "Recipe sites", "Instagram"], [
    ingredient("baby potatoes", 2, "bag", "produce", 3.7),
    ingredient("romaine hearts", 1, "bag", "produce", 3.2),
    ingredient("caesar dressing", 1, "bottle", "specialty", 4.5),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
    ingredient("breadcrumbs", 1, "box", "pantry", 2.4),
  ]),
  dish("peach-burrata-toast", "Peach Burrata Toasts", "🍑", 15, "easy", ["veg", "dinner-party"], "Soft fruit and burrata is still premium-looking content for almost no effort.", ["Instagram", "Pinterest", "Recipe sites"], [
    ingredient("sourdough loaf", 1, "loaf", "bakery", 5.6),
    ingredient("peaches", 4, "piece", "produce", 1.4),
    ingredient("burrata", 2, "tub", "dairy", 6.7),
    ingredient("hot honey", 1, "bottle", "specialty", 5.5),
    ingredient("basil", 1, "bunch", "produce", 2.1),
  ]),
  dish("red-pepper-feta-lentils", "Roasted Red Pepper Feta Lentils", "🫑", 25, "easy", ["veg", "cozy"], "High-protein vegetarian bowls keep trending when they still feel cozy.", ["Recipe sites", "Pinterest", "Meal-prep"], [
    ingredient("pre-cooked lentils", 2, "pack", "pantry", 3.8),
    ingredient("roasted red peppers", 1, "jar", "specialty", 4.9),
    ingredient("feta", 1, "tub", "dairy", 4.9),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("lemons", 2, "piece", "produce", 0.8),
  ]),
  dish("honey-soy-lettuce-cups", "Honey Soy Noodle Lettuce Cups", "🥬", 25, "easy", ["quick", "protein"], "Crunchy lettuce cups look polished while staying weeknight friendly.", ["Recipe sites", "Pinterest", "Video"], [
    ingredient("ground chicken", 2, "lb", "protein", 6.1),
    ingredient("ramen noodles", 2, "pack", "pantry", 1.6),
    ingredient("butter lettuce", 2, "head", "produce", 2.9),
    ingredient("honey soy sauce", 1, "bottle", "specialty", 4.7),
    ingredient("carrots", 1, "bag", "produce", 2.4),
  ]),
  dish("al-pastor-chicken-bowls", "Al Pastor Chicken Bowls", "🍍", 30, "easy", ["spicy", "protein"], "Sweet-spicy pineapple bowls stay popular because they feel bright and fun.", ["Recipe sites", "Pinterest", "Instagram"], [
    ingredient("chicken thighs", 2, "lb", "protein", 6.8),
    ingredient("pineapple", 1, "piece", "produce", 3.8),
    ingredient("brown rice", 1, "bag", "pantry", 4.4),
    ingredient("chipotle peppers", 1, "can", "pantry", 2.3),
    ingredient("cilantro", 1, "bunch", "produce", 1.2),
  ]),
  dish("broccoli-cheddar-pot-pies", "Broccoli Cheddar White Bean Pot Pies", "🥧", 40, "medium", ["cozy", "veg"], "Mini pot pies feel nostalgic and freezer-friendly, which people love.", ["Recipe sites", "Pinterest", "Video"], [
    ingredient("puff pastry", 2, "box", "frozen", 5.7),
    ingredient("broccoli florets", 2, "bag", "produce", 3.3),
    ingredient("white beans", 2, "can", "pantry", 1.3),
    ingredient("sharp cheddar", 1, "bag", "dairy", 4.9),
    ingredient("vegetable broth", 1, "carton", "pantry", 2.6),
  ]),
  dish("chili-lime-shrimp-tostadas", "Chili Lime Shrimp Tostadas", "🌮", 20, "easy", ["quick", "spicy", "seafood"], "Tostadas keep winning because they bring crunch and color with almost no effort.", ["Recipe sites", "Pinterest", "Creator posts"], [
    ingredient("shrimp", 2, "lb", "seafood", 10.2),
    ingredient("tostada shells", 1, "pack", "bakery", 3.6),
    ingredient("avocados", 2, "piece", "produce", 1.7),
    ingredient("cabbage slaw", 1, "bag", "produce", 2.9),
    ingredient("tajin", 1, "jar", "specialty", 3.9),
  ]),
  dish("spicy-peanut-cucumber-noodles", "Spicy Peanut Cucumber Noodles", "🥒", 20, "easy", ["quick", "spicy", "veg"], "Cold spicy noodles with crunch keep cycling through every season.", ["Video", "Pinterest", "Recipe sites"], [
    ingredient("lo mein noodles", 2, "pack", "pantry", 3.4),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("peanut sauce", 1, "bottle", "specialty", 5.2),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
    ingredient("sesame seeds", 1, "jar", "pantry", 3.2),
  ]),
  dish("loaded-potato-quesadillas", "Loaded Baked Potato Quesadillas", "🧀", 25, "easy", ["cozy", "veg"], "Comfort-food mashups always outperform because they are instantly understandable.", ["Pinterest", "Recipe sites", "Instagram"], [
    ingredient("large tortillas", 1, "pack", "bakery", 3.8),
    ingredient("russet potatoes", 4, "piece", "produce", 1.0),
    ingredient("sharp cheddar", 1, "bag", "dairy", 4.9),
    ingredient("sour cream", 1, "tub", "dairy", 2.7),
    ingredient("chives", 1, "bunch", "produce", 1.9),
  ]),
  dish("thai-peanut-chicken-slaw", "Thai Peanut Chicken Slaw", "🥬", 20, "easy", ["quick", "protein", "crunchy"], "Big chopped salads with peanut dressing keep resurfacing because they feel fresh but still substantial.", ["Food.com", "Allrecipes.com", "Pinterest"], [
    ingredient("napa cabbage", 1, "head", "produce", 3.6),
    ingredient("carrots", 1, "bag", "produce", 2.4),
    ingredient("chicken breast", 2, "lb", "protein", 7.2),
    ingredient("peanut dressing", 1, "bottle", "specialty", 5.1),
    ingredient("cilantro", 1, "bunch", "produce", 1.2),
  ]),
  dish("mediterranean-chickpea-cucumber-salad", "Mediterranean Chickpea Cucumber Salad", "🥒", 15, "easy", ["quick", "veg", "fresh"], "Chopped Mediterranean salads keep trending because they look bright, expensive, and meal-prep friendly.", ["Allrecipes.com", "BigOven", "Pinterest"], [
    ingredient("chickpeas", 2, "can", "pantry", 1.2),
    ingredient("cucumber", 2, "piece", "produce", 1.2),
    ingredient("cherry tomatoes", 1, "box", "produce", 3.2),
    ingredient("feta", 1, "tub", "dairy", 4.9),
    ingredient("olives", 1, "jar", "pantry", 4.6),
  ]),
  dish("brussels-apple-farro-salad", "Brussels Apple Farro Salad", "🍏", 30, "easy", ["veg", "crunchy", "cozy"], "Shaved brussels and apple salads keep getting saved when people want something wholesome but not boring.", ["BigOven", "Food.com", "Pinterest"], [
    ingredient("farro", 1, "bag", "pantry", 4.8),
    ingredient("brussels sprouts", 1, "bag", "produce", 3.9),
    ingredient("apples", 3, "piece", "produce", 1.1),
    ingredient("goat cheese", 1, "tub", "dairy", 5.2),
    ingredient("walnuts", 1, "bag", "pantry", 6.2),
  ]),
  dish("roasted-broccoli-caesar-lentils", "Roasted Broccoli Caesar Lentils", "🥦", 30, "easy", ["veg", "protein", "cozy"], "Warm caesar-style bowls keep circulating because they split the difference between comfort food and a salad.", ["Meal-Master", "Allrecipes.com", "Pinterest"], [
    ingredient("broccoli florets", 2, "bag", "produce", 3.3),
    ingredient("pre-cooked lentils", 2, "pack", "pantry", 3.8),
    ingredient("caesar dressing", 1, "bottle", "specialty", 4.5),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
    ingredient("breadcrumbs", 1, "box", "pantry", 2.4),
  ]),
  dish("sticky-gochujang-meatball-bowls", "Sticky Gochujang Meatball Bowls", "🍚", 30, "easy", ["protein", "spicy", "meal-prep"], "Sticky meatball bowls are still a permanent internet favorite because they reheat well and look glossy on camera.", ["Allrecipes.com", "Food.com", "BigOven"], [
    ingredient("ground chicken", 2, "lb", "protein", 6.1),
    ingredient("short grain rice", 1, "bag", "pantry", 4.8),
    ingredient("gochujang", 1, "tub", "specialty", 5.9),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
  ]),
  dish("lemon-dill-salmon-potatoes", "Lemon Dill Salmon with Crispy Potatoes", "🐟", 30, "easy", ["seafood", "protein", "bright"], "Lemony salmon sheet-pan dinners keep ranking well because they feel polished without adding extra cleanup.", ["BigOven", "Allrecipes.com", "Pinterest"], [
    ingredient("salmon fillets", 2, "lb", "seafood", 11.5),
    ingredient("baby potatoes", 2, "bag", "produce", 3.7),
    ingredient("lemons", 2, "piece", "produce", 0.8),
    ingredient("dill", 1, "bunch", "produce", 1.8),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("street-cart-chicken-rice", "Street Cart Chicken and Yellow Rice", "🍗", 35, "medium", ["protein", "cozy", "meal-prep"], "Halal-cart inspired plates keep getting recreated because the sauce-and-rice combo always feels satisfying.", ["Food.com", "Meal-Master", "Pinterest"], [
    ingredient("chicken thighs", 2, "lb", "protein", 6.8),
    ingredient("yellow rice", 1, "bag", "pantry", 4.9),
    ingredient("romaine hearts", 1, "bag", "produce", 3.2),
    ingredient("tomatoes", 3, "piece", "produce", 1.1),
    ingredient("white sauce", 1, "bottle", "specialty", 5.3),
  ]),
  dish("miso-sesame-sweet-potato-bowls", "Miso Sesame Sweet Potato Bowls", "🍠", 30, "easy", ["veg", "cozy", "protein"], "Sweet potato grain bowls keep doing well online because the color contrast makes them look more elaborate than they are.", ["Meal-Master", "BigOven", "Pinterest"], [
    ingredient("sweet potatoes", 3, "piece", "produce", 1.3),
    ingredient("brown rice", 1, "bag", "pantry", 4.4),
    ingredient("extra firm tofu", 2, "block", "protein", 2.9),
    ingredient("white miso", 1, "tub", "specialty", 5.7),
    ingredient("sesame seeds", 1, "jar", "pantry", 3.2),
  ]),
  dish("creamy-corn-miso-rigatoni", "Creamy Corn Miso Rigatoni", "🌽", 25, "easy", ["cozy", "veg", "quick"], "Sweet corn plus savory pasta keeps landing in roundups because it reads summery and comforting at the same time.", ["Allrecipes.com", "BigOven", "Pinterest"], [
    ingredient("rigatoni", 1, "box", "pantry", 3.1),
    ingredient("frozen corn", 1, "bag", "frozen", 3.1),
    ingredient("white miso", 1, "tub", "specialty", 5.7),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
  ]),
  dish("roasted-red-pepper-tortellini", "Roasted Red Pepper Tortellini Skillet", "🍝", 20, "easy", ["quick", "cozy", "veg"], "Creamy tortellini skillets keep overperforming because they look rich and fast in the same post.", ["Food.com", "Allrecipes.com", "Pinterest"], [
    ingredient("cheese tortellini", 2, "pack", "frozen", 5.9),
    ingredient("roasted red peppers", 1, "jar", "specialty", 4.9),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("cream sauce", 1, "jar", "pantry", 4.7),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("sesame-garlic-chicken-ramen", "Sesame Garlic Chicken Ramen", "🍜", 25, "easy", ["quick", "protein", "cozy"], "Upgrade-your-ramen dinners keep staying popular because they feel clever, cheap, and very clickable.", ["BigOven", "Food.com", "Meal-Master"], [
    ingredient("ramen noodles", 2, "pack", "pantry", 1.6),
    ingredient("chicken breast", 2, "lb", "protein", 7.2),
    ingredient("sesame ginger sauce", 1, "bottle", "specialty", 5.3),
    ingredient("broccoli florets", 2, "bag", "produce", 3.3),
    ingredient("scallions", 1, "bunch", "produce", 1.2),
  ]),
  dish("spinach-artichoke-orzo-bake", "Spinach Artichoke Orzo Bake", "🥘", 35, "medium", ["cozy", "veg", "bake"], "Spinach-artichoke anything still gets traction, and baked orzo makes it feel weeknight-capable.", ["Meal-Master", "Allrecipes.com", "BigOven"], [
    ingredient("orzo", 1, "box", "pantry", 2.9),
    ingredient("artichoke hearts", 1, "jar", "pantry", 4.8),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("mozzarella", 1, "bag", "dairy", 4.5),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("marry-me-chickpeas-orzo", "Marry Me Chickpeas and Orzo", "🍅", 30, "easy", ["cozy", "veg", "one-pan"], "The 'marry me' flavor profile is still all over recipe feeds, especially when it gets applied to pantry staples.", ["Allrecipes.com", "Food.com", "BigOven"], [
    ingredient("orzo", 1, "box", "pantry", 2.9),
    ingredient("chickpeas", 2, "can", "pantry", 1.2),
    ingredient("sun-dried tomatoes", 1, "jar", "pantry", 5.2),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("smoky-sausage-white-beans", "Smoky Sausage White Bean Skillet", "🥘", 30, "easy", ["protein", "cozy", "one-pan"], "Sausage and beans keeps resurfacing because it feels rustic, filling, and forgiving.", ["Food.com", "Meal-Master", "Allrecipes.com"], [
    ingredient("chicken sausage", 2, "lb", "protein", 7.1),
    ingredient("white beans", 2, "can", "pantry", 1.3),
    ingredient("cherry tomatoes", 1, "box", "produce", 3.2),
    ingredient("kale", 1, "bag", "produce", 3.1),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("coconut-chicken-rice-pot", "Coconut Chicken Rice Pot", "🥥", 35, "medium", ["protein", "one-pot", "cozy"], "One-pot coconut rice dinners stay sticky online because the texture looks luxurious and the cleanup story is simple.", ["BigOven", "Allrecipes.com", "Pinterest"], [
    ingredient("chicken thighs", 2, "lb", "protein", 6.8),
    ingredient("jasmine rice", 1, "bag", "pantry", 4.5),
    ingredient("coconut milk", 2, "can", "pantry", 2.8),
    ingredient("baby spinach", 1, "bag", "produce", 2.8),
    ingredient("lime", 2, "piece", "produce", 0.7),
  ]),
  dish("tomato-basil-risoni-skillet", "Tomato Basil Risoni Skillet", "🍅", 20, "easy", ["quick", "cozy", "veg"], "Saucy risoni skillets keep popping because they look like restaurant pasta but eat like pantry food.", ["Meal-Master", "BigOven", "Food.com"], [
    ingredient("risoni", 1, "box", "pantry", 3.0),
    ingredient("cherry tomatoes", 1, "box", "produce", 3.2),
    ingredient("vegetable broth", 1, "carton", "pantry", 2.6),
    ingredient("mozzarella", 1, "bag", "dairy", 4.5),
    ingredient("basil", 1, "bunch", "produce", 2.1),
  ]),
  dish("smash-chicken-caesar-wraps", "Smash Chicken Caesar Wraps", "🌯", 20, "easy", ["quick", "protein", "handheld"], "Caesar wraps keep cycling through creator posts because they are familiar, crisp, and easy to meal prep.", ["Allrecipes.com", "Food.com", "Pinterest"], [
    ingredient("large tortillas", 1, "pack", "bakery", 3.8),
    ingredient("ground chicken", 2, "lb", "protein", 6.1),
    ingredient("romaine hearts", 1, "bag", "produce", 3.2),
    ingredient("caesar dressing", 1, "bottle", "specialty", 4.5),
    ingredient("parmesan", 1, "tub", "dairy", 5.8),
  ]),
  dish("greek-turkey-pita-burgers", "Greek Turkey Pita Burgers", "🍔", 30, "easy", ["protein", "fresh", "handheld"], "Greek-style burgers stay relevant because the toppings feel bright while the format still scratches a comfort-food itch.", ["BigOven", "Allrecipes.com", "Pinterest"], [
    ingredient("ground turkey", 2, "lb", "protein", 5.9),
    ingredient("pita", 1, "pack", "bakery", 3.9),
    ingredient("cucumbers", 2, "piece", "produce", 1.2),
    ingredient("tomatoes", 3, "piece", "produce", 1.1),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("chipotle-black-bean-crunchwraps", "Chipotle Black Bean Crunchwraps", "🌮", 25, "easy", ["veg", "spicy", "handheld"], "Crunchwrap-style dinners keep getting remixed because they deliver maximum fun with grocery-store ingredients.", ["Food.com", "Meal-Master", "Pinterest"], [
    ingredient("large tortillas", 1, "pack", "bakery", 3.8),
    ingredient("black beans", 2, "can", "pantry", 1.3),
    ingredient("tostada shells", 1, "pack", "bakery", 3.6),
    ingredient("cheddar", 1, "bag", "dairy", 4.6),
    ingredient("chipotle crema", 1, "bottle", "specialty", 4.9),
  ]),
  dish("bbq-salmon-slaw-sliders", "BBQ Salmon Slaw Sliders", "🍔", 25, "easy", ["seafood", "handheld", "fresh"], "Mini seafood sandwiches keep getting saves because they feel a little different without being difficult.", ["BigOven", "Food.com", "Allrecipes.com"], [
    ingredient("salmon fillets", 2, "lb", "seafood", 11.5),
    ingredient("slider buns", 1, "pack", "bakery", 4.9),
    ingredient("coleslaw mix", 1, "bag", "produce", 2.9),
    ingredient("bbq sauce", 1, "bottle", "specialty", 4.2),
    ingredient("pickles", 1, "jar", "pantry", 3.8),
  ]),
  dish("white-chicken-enchilada-soup", "White Chicken Enchilada Soup", "🥣", 30, "easy", ["protein", "cozy", "spicy"], "Creamy enchilada-inspired soups stay in heavy rotation because the topping bar makes them feel flexible and fun.", ["Allrecipes.com", "Food.com", "BigOven"], [
    ingredient("chicken breast", 2, "lb", "protein", 7.2),
    ingredient("green chiles", 2, "can", "pantry", 1.8),
    ingredient("white beans", 2, "can", "pantry", 1.3),
    ingredient("chicken broth", 2, "carton", "pantry", 2.9),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("lasagna-soup", "Weeknight Lasagna Soup", "🍲", 35, "medium", ["cozy", "protein", "soup"], "Lasagna soup keeps sticking around because it promises the flavor payoff without the full layering commitment.", ["Food.com", "BigOven", "Meal-Master"], [
    ingredient("ground beef", 2, "lb", "protein", 6.4),
    ingredient("lasagna noodles", 1, "box", "pantry", 3.4),
    ingredient("tomato soup", 2, "carton", "pantry", 3.6),
    ingredient("mozzarella", 1, "bag", "dairy", 4.5),
    ingredient("basil", 1, "bunch", "produce", 2.1),
  ]),
  dish("smoky-lentil-sweet-potato-chili", "Smoky Lentil Sweet Potato Chili", "🌶️", 40, "medium", ["veg", "cozy", "meal-prep"], "Vegetarian chilis with sweet potatoes keep circulating because they feel hearty, colorful, and freezer-friendly.", ["Meal-Master", "Allrecipes.com", "Pinterest"], [
    ingredient("pre-cooked lentils", 2, "pack", "pantry", 3.8),
    ingredient("sweet potatoes", 3, "piece", "produce", 1.3),
    ingredient("chipotle peppers", 1, "can", "pantry", 2.3),
    ingredient("tomato soup", 2, "carton", "pantry", 3.6),
    ingredient("greek yogurt", 1, "tub", "dairy", 4.7),
  ]),
  dish("ginger-coconut-rice-soup", "Ginger Coconut Rice Soup", "🥥", 25, "easy", ["cozy", "soup", "veg"], "Brothy coconut soups stay popular because they feel restorative and still look dramatic in a bowl.", ["BigOven", "Meal-Master", "Pinterest"], [
    ingredient("jasmine rice", 1, "bag", "pantry", 4.5),
    ingredient("coconut milk", 2, "can", "pantry", 2.8),
    ingredient("baby bok choy", 2, "head", "produce", 2.2),
    ingredient("mushrooms", 2, "box", "produce", 2.9),
    ingredient("ginger sauce", 1, "bottle", "specialty", 4.8),
  ]),
];
